language: node_js
node_js:
  - 0.11
  - 0.12
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install imagemagick libmagickwand-dev libmagickcore-dev libgif-dev
  - npm install
  - git clone https://github.com/nna774/piet-testutils.git
  - cd piet-testutils
  - npm install
  - node app.js devide_by_2.10cs.11x4.png
  - sed -i -e "s/var codel = 10;/var codel = 1;/" config.js
  - cd ..
script:
  - make all
  - TESTUTILS_REL=piet-testutils ./test.sh
  - make clean
  - sed -i -e "s/var size = 3;/var size = 5;/" config.js
  - make all
  - TESTUTILS_REL=piet-testutils ./test.sh
  - make clean
  - sed -i -e "s/var size = 5;/var size = 7;/" config.js
  - make all
  - TESTUTILS_REL=piet-testutils ./test.sh
