language: node_js
node_js:
  - 5.11
  - 6
  - 6.1
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgif-dev
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - g++-4.8
env:
  - CXX=g++-4.8
install:
  - $CXX --version
  - npm install
  - git clone https://github.com/nna774/piet-testutils.git
  - cd piet-testutils
  - npm install
  - node --use_strict app.js devide_by_2.10cs.11x4.png
  - sed -i -e "s/const codel = 10;/const codel = 1;/" config.js
  - cd ..
script:
  - make lint
  - make all
  - TESTUTILS_REL=piet-testutils ./test.sh
  - make clean
  - sed -i -e "s/const size = 3;/const size = 5;/" config.js
  - make all
  - TESTUTILS_REL=piet-testutils ./test.sh
  - make clean
  - sed -i -e "s/const size = 5;/const size = 7;/" config.js
  - make all
  - TESTUTILS_REL=piet-testutils ./test.sh
