language: node_js
node_js:
  - 0.11
  - 0.12
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install imagemagick libmagickwand-dev libmagickcore-dev libgif-dev
  - npm install
  - git clone https://github.com/nna774/piet-testutils.git
  - node app.js tests/puts72.pas puts72.png
  - node app.js tests/puts72_2.pas puts72_2.png
  - node app.js tests/even-or-odd.pas even-or-odd.png
  - node app.js tests/helloworld.pas helloworld.png
  - node app.js tests/helloworld_2.pas helloworld_2.png
  - node app.js tests/jmp_2.pas jmp_2.png
  - node app.js tests/jmp_3.pas jmp_3.png
  - node app.js tests/gcd.pas gcd.png
  - node app.js tests/swap.pas swap.png
  - node app.js tests/lisp-like-calc.pas lisp-like-calc.png
  - cd piet-testutils
  - npm install
  - node app.js devide_by_2.10cs.11x4.png
  - sed -i -e "s/var codel = 10;/var codel = 1;/" config.js
  - cp ../tests/tests/puts72.js tests.js
  - node app.js ../puts72.png
  - node app.js ../puts72_2.png
  - cp ../tests/tests/even-or-odd.js tests.js
  - node app.js ../even-or-odd.png
  - cp ../tests/tests/helloworld.js tests.js
  - node app.js ../helloworld.png
  - node app.js ../helloworld_2.png
  - cp ../tests/tests/puts1.js tests.js
  - node app.js ../jmp_2.png
  - node app.js ../jmp_3.png
  - cp ../tests/tests/gcd.js tests.js
  - node app.js ../gcd.png
  - cp ../tests/tests/swap.js tests.js
  - node app.js ../swap.png
  - cp ../tests/tests/lisp-like-calc.js tests.js
  - node app.js ../lisp-like-calc.png
