var size = 7;

var images = {
    'push': { 'file': 'piet/7x7/push1.png' },
    'push0': { 'file': 'piet/7x7/push0.png' },
    'push2': { 'file': 'piet/7x7/push2.png' },
    'push16': { 'file': 'piet/7x7/push16.png' },
    'push32': { 'file': 'piet/7x7/push32.png' },
    'pop': { 'file': 'piet/7x7/pop.png' },
    'add': { 'file': 'piet/7x7/add.png' },
    'sub': { 'file': 'piet/7x7/sub.png' },
    'mul': { 'file': 'piet/7x7/mul.png' },
    'div': { 'file': 'piet/7x7/div.png' },
    'mod': { 'file': 'piet/7x7/mod.png' },
    'not': { 'file': 'piet/7x7/not.png' },
    'greater': { 'file': 'piet/7x7/great.png' },
    'dup': { 'file': 'piet/7x7/dup.png' },
    'dupadd': { 'file': 'piet/7x7/dupadd.png' },
    'dupmul': { 'file': 'piet/7x7/dupmul.png' },
    'roll': { 'file': 'piet/7x7/roll.png' },
    'in_n': { 'file': 'piet/7x7/in_n.png' },
    'in_c': { 'file': 'piet/7x7/in_c.png' },
    'out_n': { 'file': 'piet/7x7/out_n.png' },
    'out_c': { 'file': 'piet/7x7/out_c.png' },
    'nop_h': { 'file': 'piet/7x7/nop_h.png' },
    'nop_v': { 'file': 'piet/7x7/nop_v.png' },
    'cross': { 'file': 'piet/7x7/cross.png' },
    'curve': { 'file': 'piet/7x7/curve1.png' },
    'join': { 'file': 'piet/7x7/join.png' },
    'branch': { 'file': 'piet/7x7/branch.png' },
    'notbranch': { 'file': 'piet/7x7/notbranch.png' },
    'nop_v': { 'file': 'piet/7x7/nop_v.png' },
    'start': { 'file': 'piet/7x7/start.png' },
    'terminate': { 'file': 'piet/7x7/terminate.png' },
    'black': { 'file': 'piet/7x7/black.png' },
    'branch': { 'file': 'piet/7x7/branch.png' },
    'curve1': { 'file': 'piet/7x7/curve1.png' },
    'curve4': { 'file': 'piet/7x7/curve4.png' },
    'curve5': { 'file': 'piet/7x7/curve5.png' },
    'curve6': { 'file': 'piet/7x7/curve6.png' },
    'curve7': { 'file': 'piet/7x7/curve7.png' },
    'rjoin': { 'file': 'piet/7x7/rjoin.png' },
    'ljoin': { 'file': 'piet/7x7/ljoin.png' },
    'swap': { 'file': 'piet/7x7/swap.png' },
};

module.exports = {
    images: images,
    unit: size,
};
