var images = {
    'push': { 'file': 'piet/push1.png' },
    'pop': { 'file': 'piet/pop.png' },
    'add': { 'file': 'piet/add.png' },
    'sub': { 'file': 'piet/sub.png' },
    'mul': { 'file': 'piet/mul.png' },
    'div': { 'file': 'piet/div.png' },
    'mod': { 'file': 'piet/mod.png' },
    'not': { 'file': 'piet/not.png' },
    'greater': { 'file': 'piet/great.png' },
    'dup': { 'file': 'piet/dup.png' },
    'roll': { 'file': 'piet/roll.png' },
    'in_n': { 'file': 'piet/in_n.png' },
    'in_c': { 'file': 'piet/in_c.png' },
    'out_n': { 'file': 'piet/out_n.png' },
    'out_c': { 'file': 'piet/out_c.png' },
    'nop': { 'file': 'piet/nop_h.png' },
    'nop_v': { 'file': 'piet/nop_v.png' },
    'cross': { 'file': 'piet/cross.png' },
    'curve': { 'file': 'piet/curve1.png' },
    'join': { 'file': 'piet/join.png' },
    'branch': { 'file': 'piet/branch.png' },
    'nop_v': { 'file': 'piet/nop_v.png' },
    'start': { 'file': 'piet/start.png' },
    'terminate': { 'file': 'piet/terminate.png' },
};

module.exports = {
    images: images,
    unit: 5,
};
