var images = {
    'push': { 'file': 'piet/push1.png' },
    'push0': { 'file': 'piet/push0.png' },
    'push2': { 'file': 'piet/push2.png' },
    'push16': { 'file': 'piet/push16.png' },
    'push32': { 'file': 'piet/push32.png' },
    'pop': { 'file': 'piet/pop.png' },
    'add': { 'file': 'piet/add.png' },
    'sub': { 'file': 'piet/sub.png' },
    'mul': { 'file': 'piet/mul.png' },
    'div': { 'file': 'piet/div.png' },
    'mod': { 'file': 'piet/mod.png' },
    'not': { 'file': 'piet/not.png' },
    'greater': { 'file': 'piet/great.png' },
    'dup': { 'file': 'piet/dup.png' },
    'dupadd': { 'file': 'piet/dupadd.png' },
    'dupmul': { 'file': 'piet/dupmul.png' },
    'roll': { 'file': 'piet/roll.png' },
    'in_n': { 'file': 'piet/in_n.png' },
    'in_c': { 'file': 'piet/in_c.png' },
    'out_n': { 'file': 'piet/out_n.png' },
    'out_c': { 'file': 'piet/out_c.png' },
    'nop_h': { 'file': 'piet/nop_h.png' },
    'nop_v': { 'file': 'piet/nop_v.png' },
    'cross': { 'file': 'piet/cross.png' },
    'curve': { 'file': 'piet/curve1.png' },
    'join': { 'file': 'piet/join.png' },
    'branch': { 'file': 'piet/branch.png' },
    'notbranch': { 'file': 'piet/notbranch.png' },
    'nop_v': { 'file': 'piet/nop_v.png' },
    'start': { 'file': 'piet/start.png' },
    'terminate': { 'file': 'piet/terminate.png' },
    'black': { 'file': 'piet/black.png' },
    'branch': { 'file': 'piet/branch.png' },
    'curve1': { 'file': 'piet/curve1.png' },
    'curve4': { 'file': 'piet/curve4.png' },
    'curve5': { 'file': 'piet/curve5.png' },
    'curve6': { 'file': 'piet/curve6.png' },
    'curve7': { 'file': 'piet/curve7.png' },
    'rjoin': { 'file': 'piet/rjoin.png' },
    'ljoin': { 'file': 'piet/ljoin.png' },
    'swap': { 'file': 'piet/swap.png' },
};

module.exports = {
    images: images,
    unit: 7,
};
